tw5864-objs := tw5864-core.o tw5864-video.o tw5864-config.o tw5864-h264.o h264bitstream/h264_stream.o h264bitstream/h264_sei.o h264bitstream/h264_avcc.o h264bitstream/h264_nal.o

ccflags-y += -std=gnu99 -Wno-declaration-after-statement

obj-$(CONFIG_VIDEO_TW5864) += tw5864.o
