#ccflags-y := -Wno-error=incompatible-pointer-types

LXV4L2D-objs := LINUXV4L2.o wrapper.o property.o tw6805.o cx2581.o cx2588.o sa7160.o sl6010.o ah8400.o tw5864.o fh8735.o ite6603.o mst3367.o mz0380.o

obj-$(CONFIG_VIDEO_ISIL5864) += LXV4L2D.o
